// Catálogo de respaldo local — alimenta tanto el buscador del Header como la
// grilla principal del menú, así ambos quedan siempre sincronizados aunque
// Supabase no esté conectado.
export const PRODUCTOS_MOCK = [
  { id: 'mock-1', nombre: 'Burger Clásica', categoria: 'Hamburguesas', precio: 8.5, precio_original: null, descripcion: 'Carne 100% de res, queso cheddar, lechuga, tomate y salsa especial.', imagen_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&auto=format&fit=crop&q=60', emoji: '🍔', disponible: true },
  { id: 'mock-2', nombre: 'Burger Doble Queso', categoria: 'Hamburguesas', precio: 10.99, precio_original: null, descripcion: 'Doble carne, doble cheddar fundido, tocino crujiente y cebolla caramelizada.', imagen_url: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=500&auto=format&fit=crop&q=60', emoji: '🍔', disponible: true },
  { id: 'mock-3', nombre: 'Pizza Pepperoni', categoria: 'Pizzas', precio: 12.5, precio_original: null, descripcion: 'Masa madre crujiente, salsa de tomate artesanal, mozzarella y abundante pepperoni.', imagen_url: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=500&auto=format&fit=crop&q=60', emoji: '🍕', disponible: true },
  { id: 'mock-4', nombre: 'Pizza Hawaiana', categoria: 'Pizzas', precio: 11.0, precio_original: null, descripcion: 'La combinación perfecta de jamón dulce, piña jugosa y queso fundido.', imagen_url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=500&auto=format&fit=crop&q=60', emoji: '🍕', disponible: true },
  { id: 'mock-5', nombre: 'Salchipapa Especial', categoria: 'Rápidas', precio: 6.0, precio_original: null, descripcion: 'Papas doradas crujientes, salchicha artesanal, chorizo, huevo de codorniz y salsas de la casa.', imagen_url: 'https://images.unsplash.com/photo-1585109649139-366815a0d713?w=500&auto=format&fit=crop&q=60', emoji: '🍟', disponible: true },
  { id: 'mock-6', nombre: 'Coca-Cola 1.5L', categoria: 'Bebidas', precio: 2.5, precio_original: null, descripcion: 'Bebida helada para acompañar tu platillo favorito.', imagen_url: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=60', emoji: '🥤', disponible: true },
];
